local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>fr', function()
    require('telescope.builtin').lsp_references()
end)
vim.keymap.set('n', 'gr', function()
    require('telescope.builtin').lsp_references()
end)
vim.keymap.set('n', 'gd', function()
    require('telescope.builtin').lsp_definitions()
end)
vim.keymap.set('n', 'go', function()
    require('telescope.builtin').lsp_type_definitions()
end)
